baseURL = 'https://onwuachi.com/'
languageCode = 'en-us'
title = 'Onwuachi Control Plane'

# Ignore bak files
ignoreFiles = ['.*-bak$', '.*\.bak$']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true   # allow raw HTML in markdown

[build]
  writeStats = true

[taxonomies]
  distillery = "distilleries"
  brand = "brands"
  style = "styles"
  producer = "producers"
