name: Manage Onwuachi Web Server

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action (start, stop, upgrade)"
        required: true
        default: "start"
        type: choice
        options:
          - start
          - stop
          - upgrade

permissions:
  id-token: write
  contents: read

jobs:
  manage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::046685909731:role/github-oidc-role
          aws-region: us-east-1

      - name: Run selected action via SSM
        run: |
          chmod +x scripts/manage-web.sh
          ./scripts/manage-web.sh "${{ github.event.inputs.action }}"
