name: platform-schedule

on:
  schedule:

    # 11:15 PM Central Time (CDT = UTC-5)
    - cron: '15 4 * * *'

    # 6:15 AM Central Time (CDT = UTC-5)
    - cron: '15 11 * * *'

  workflow_dispatch:

jobs:
  platform-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Make platform executable
        run: chmod +x tools/platform

      ########################################
      # PLATFORM DOWN (11:15 PM CT)
      ########################################

      - name: Shutdown platform nightly
        if: github.event.schedule == '15 4 * * *'
        run: |
          ./tools/platform down

      ########################################
      # PLATFORM UP (6:15 AM CT)
      ########################################

      - name: Start platform daily
        if: github.event.schedule == '15 11 * * *'
        run: |
          ./tools/platform up